#
# Copyright (c) 2005 X.Org Foundation LLC
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#
# Copyright (c) Applied Testing and Technology, Inc. 1993, 1994, 1995
# Copyright (c) 88open Consortium, Ltd. 1990, 1991, 1992, 1993
# All Rights Reserved.
#
# Project: VSW5
#
# File: xts5/src/lib/libXR5/Makefile
#
# Description: Makefile for libXR5
#
# Modifications
# $Log: Makefile,v $
# Revision 1.2  2005-11-03 08:42:02  jmichael
# clean up all vsw5 paths to use xts5 instead.
#
# Revision 1.1.1.1  2005/02/12 15:14:15  anderson
# VSW5 Source under an MIT license This is version 5.0.2 as received from
# AppTest with the new license applied.
#
# Revision 8.0  1998/12/23 23:25:44  mar
# Branch point for Release 5.0.2
#
# Revision 7.0  1998/10/30 22:43:58  mar
# Branch point for Release 5.0.2b1
#
# Revision 6.0  1998/03/02 05:18:02  tbr
# Branch point for Release 5.0.1
#
# Revision 5.0  1998/01/26 03:14:34  tbr
# Branch point for Release 5.0.1b1
#
# Revision 4.1  1996/01/25 02:34:04  andy
# Added IGNORE target
#
# Revision 4.0  1995/12/15  08:45:45  tbr
# Branch point for Release 5.0.0
#
# Revision 3.1  1995/12/15  00:43:29  andy
# Prepare for GA Release
#

.IGNORE:

CFILES = r5startup.c message.c dumpbuf.c save.c misc.c blowup.c item.c signal.c bufdisp.c chek.c event.c

OFILES = r5startup.o message.o dumpbuf.o save.o misc.o blowup.o item.o signal.o bufdisp.o chek.o event.o

RM_FILES = *.o core *.a

all: libXR5.a 

libXR5.a: $(OFILES)
		@$(AR) $@ `$(LORDER) $(OFILES) | $(TSORT)`
		: $(RANLIB) $@


.c.o:
	$(CC) -DDEBUG -c $(CFLAGS) $<

install: all
	$(CP) libXR5.a $(XTESTLIBDIR)
	@$(RANLIB) $(XTESTLIBDIR)/libXR5.a

FORCE:		CLOBBER all

clean:
		@$(RM) -f $(RM_FILES)

clobber:	clean
