#
# Copyright (c) 2005 X.Org Foundation LLC
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#
# Copyright (c) Applied Testing and Technology, Inc. 1995
# All Rights Reserved.
#
# Project: VSW5
#
# File: xts5/src/lib/Makefile
#
# Description: Makefile for X testsuite library
#
# Modifications
# $Log: Makefile,v $
# Revision 1.2  2005-11-03 08:42:01  jmichael
# clean up all vsw5 paths to use xts5 instead.
#
# Revision 1.1.1.1  2005/02/12 15:14:15  anderson
# VSW5 Source under an MIT license This is version 5.0.2 as received from
# AppTest with the new license applied.
#
# Revision 8.0  1998/12/23 23:24:20  mar
# Branch point for Release 5.0.2
#
# Revision 7.0  1998/10/30 22:42:30  mar
# Branch point for Release 5.0.2b1
#
# Revision 6.0  1998/03/02 05:16:46  tbr
# Branch point for Release 5.0.1
#
# Revision 5.0  1998/01/26 03:13:19  tbr
# Branch point for Release 5.0.1b1
#
# Revision 4.2  1996/03/22 16:56:57  andy
# removed excess tabs and space from blank lines
#
# Revision 4.1  1996/01/25  02:33:29  andy
# Added IGNORE target
#
# Revision 4.0  1995/12/15  08:41:37  tbr
# Branch point for Release 5.0.0
#
# Revision 3.1  1995/12/15  00:38:38  andy
# Prepare for GA Release
#

# Portions of this software are based on Xlib and X Protocol Test Suite.
# We have used this material under the terms of its copyright, which grants
# free use, subject to the conditions below.  Note however that those
# portions of this software that are based on the original Test Suite have
# been significantly revised and that all such revisions are copyright (c)
# 1995 Applied Testing and Technology, Inc.  Insomuch as the proprietary
# revisions cannot be separated from the freely copyable material, the net
# result is that use of this software is governed by the ApTest copyright.
#
# Copyright (c) 1990, 1991  X Consortium
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# X CONSORTIUM BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
# AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# 
# Except as contained in this notice, the name of the X Consortium shall not be
# used in advertising or otherwise to promote the sale, use or other dealings
# in this Software without prior written authorization from the X Consortium.
#
# Copyright 1990, 1991 UniSoft Group Limited.
#
# Permission to use, copy, modify, distribute, and sell this software and
# its documentation for any purpose is hereby granted without fee,
# provided that the above copyright notice appear in all copies and that
# both that copyright notice and this permission notice appear in
# supporting documentation, and that the names of MIT and UniSoft not be
# used in advertising or publicity pertaining to distribution of the
# software without specific, written prior permission.  MIT and UniSoft
# make no representations about the suitability of this software for any
# purpose.  It is provided "as is" without express or implied warranty.

.IGNORE:

CFILES =	startup.c ex_startup.c \
	lookupname.c err.c getevent.c stackorder.c report.c \
	iponlywin.c badwin.c startcall.c makewin.c checkevent.c \
	nextvclass.c badgc.c badpixm.c badfont.c badvis.c linkstart.c \
	issuppvis.c checkarea.c getsize.c pattern.c crechild.c checktile.c \
	makepixm.c nextvinf.c makegc.c dumpimage.c verimage.c dset.c \
	delete.c rpt.c \
	savimage.c checkpixel.c notmember.c setline.c checkgc.c gcflush.c \
	tpstartup.c nondpth1pix.c gcinclude.c regid.c openfonts.c checkfont.c \
	badcmap.c makecolmap.c makecur.c makeimg.c checkimg.c opendisp.c \
	bitcount.c config.c makewin2.c block.c winh.c pointer.c events.c \
	gettime.c maxsize.c buildtree.c exposechk.c \
	settimeout.c makeregion.c xthost.c pfcount.c XTestExt.c devcntl.c \
	extenavail.c environ.c cursor.c XInput.c
OFILES =	startup.o ex_startup.o \
	lookupname.o err.o getevent.o stackorder.o report.o \
	iponlywin.o badwin.o startcall.o makewin.o checkevent.o \
	nextvclass.o badgc.o badpixm.o badfont.o badvis.o linkstart.o \
	issuppvis.o checkarea.o getsize.o pattern.o crechild.o checktile.o \
	makepixm.o nextvinf.o makegc.o dumpimage.o verimage.o dset.o \
	delete.o rpt.o \
	savimage.o checkpixel.o notmember.o setline.o checkgc.o gcflush.o \
	tpstartup.o nondpth1pix.o gcinclude.o regid.o openfonts.o checkfont.o \
	badcmap.o makecolmap.o makecur.o makeimg.o checkimg.o opendisp.o \
	bitcount.o config.o makewin2.o block.o winh.o pointer.o events.o \
	gettime.o maxsize.o buildtree.o exposechk.o \
	settimeout.o makeregion.o xthost.o pfcount.o XTestExt.o devcntl.o \
	extenavail.o environ.o cursor.o XInput.o

RM_FILES = *.ln *.o core *.a

##############################################################################

all: $(XTESTINCDIR)/xtestlib.h libxtest.a 

libxtest.a: $(OFILES)
		@$(AR) $@ `$(LORDER) $(OFILES) | $(TSORT)`
		: $(RANLIB) $@


.c.o:
	$(CC) -c $(CFLAGS) $<

install: all
	$(CP) libxtest.a $(XTESTLIB)
	@$(RANLIB) $(XTESTLIB)

FORCE:		CLOBBER all

LINT:
		$(LINT) $(LINTFLAGS) $(CFILES) $(LINTTCM) $(LINTLIBS)

LINTLIB:	$(LINTXTEST)

$(LINTXTEST):	llib-lxtest.ln
		cp $? $@

llib-lxtest.ln: $(CFILES)
		echo $(CFILES) | sed -e 's/linkstart.c //' >/tmp/Lint$$$$.tmp; \
		$(LINT) -Cxtest $(LINTFLAGS) `cat /tmp/Lint$$$$.tmp` ; \
		rm -f Lint$$$$.tmp

clean:
		$(RM) $(RM_FILES)

clobber:	clean

doc:
	ctodoc $(CFILES) > ../../doc/xtestraw.mm

xtlibproto.h: $(CFILES)
	mkxtl $(CFILES) > xtlibproto.h
	$(RM) $(XTESTINCDIR)/xtlibproto.h 
	$(CP) xtlibproto.h $(XTESTINCDIR)

tags:	$(CFILES)
	ctags $(CFILES) > tags 2> /dev/null
